<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-21T13:28:20 EDT" name="Suite" finished-at="2021-07-21T13:29:52 EDT" duration-ms="92224">
    <groups>
      <group name="hk">
        <method signature="AirCanadaTest.hh()[pri:2, instance:Tests.AirCanadaTest@7098b907]" name="hh" class="Tests.AirCanadaTest"/>
        <method signature="AirCanadaTest.ff()[pri:3, instance:Tests.AirCanadaTest@7098b907]" name="ff" class="Tests.AirCanadaTest"/>
      </group> <!-- hk -->
    </groups>
    <test started-at="2021-07-21T13:28:20 EDT" name="Test" finished-at="2021-07-21T13:29:52 EDT" duration-ms="92224">
      <class name="Tests.AirCanadaTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:28:20 EDT" name="beforeMethod" finished-at="2021-07-21T13:28:35 EDT" duration-ms="14975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TicketBooking()[pri:1, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:28:35 EDT" name="TicketBooking" finished-at="2021-07-21T13:28:44 EDT" duration-ms="8978" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TicketBooking -->
        <test-method is-config="true" signature="afertMethod()[pri:0, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:28:44 EDT" name="afertMethod" finished-at="2021-07-21T13:28:48 EDT" duration-ms="3981" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afertMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:28:48 EDT" name="beforeMethod" finished-at="2021-07-21T13:29:01 EDT" duration-ms="13037" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="hh()[pri:2, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:29:01 EDT" name="hh" finished-at="2021-07-21T13:29:03 EDT" duration-ms="1432" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hh -->
        <test-method is-config="true" signature="afertMethod()[pri:0, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:29:03 EDT" name="afertMethod" finished-at="2021-07-21T13:29:07 EDT" duration-ms="4873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afertMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:29:07 EDT" name="beforeMethod" finished-at="2021-07-21T13:29:23 EDT" duration-ms="15493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="ff()[pri:3, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:29:23 EDT" name="ff" finished-at="2021-07-21T13:29:24 EDT" depends-on-methods="Tests.AirCanadaTest.hh" duration-ms="1511" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The Hover is working expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The Hover is working expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Pages.TicketPage.Hover(TicketPage.java:79)
at Tests.AirCanadaTest.ff(AirCanadaTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ff -->
        <test-method is-config="true" signature="afertMethod()[pri:0, instance:Tests.AirCanadaTest@7098b907]" started-at="2021-07-21T13:29:24 EDT" name="afertMethod" finished-at="2021-07-21T13:29:30 EDT" duration-ms="5162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afertMethod -->
      </class> <!-- Tests.AirCanadaTest -->
      <class name="Tests.Login">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.Login@3cce57c7]" started-at="2021-07-21T13:29:30 EDT" name="beforeMethod" finished-at="2021-07-21T13:29:43 EDT" duration-ms="13795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="LoginUdemy()[pri:0, instance:Tests.Login@3cce57c7]" started-at="2021-07-21T13:29:43 EDT" name="LoginUdemy" finished-at="2021-07-21T13:29:49 EDT" duration-ms="6072" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Tests.Login.LoginUdemy(Login.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginUdemy -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Tests.Login@3cce57c7]" started-at="2021-07-21T13:29:49 EDT" name="afterMethod" finished-at="2021-07-21T13:29:52 EDT" duration-ms="2875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Tests.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
