<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-10T13:07:08 EDT" name="Suite" finished-at="2021-09-10T13:11:11 EDT" duration-ms="242953">
    <groups>
      <group name="hk">
        <method signature="AirCanadaTest.hh()[pri:2, instance:Tests.AirCanadaTest@7690781]" name="hh" class="Tests.AirCanadaTest"/>
        <method signature="AirCanadaTest.ff()[pri:3, instance:Tests.AirCanadaTest@7690781]" name="ff" class="Tests.AirCanadaTest"/>
      </group> <!-- hk -->
    </groups>
    <test started-at="2021-09-10T13:07:08 EDT" name="Test" finished-at="2021-09-10T13:11:11 EDT" duration-ms="242953">
      <class name="Tests.AirCanadaTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:07:09 EDT" name="beforeMethod" finished-at="2021-09-10T13:09:10 EDT" duration-ms="121202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TicketBooking()[pri:1, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:09:10 EDT" name="TicketBooking" finished-at="2021-09-10T13:09:25 EDT" duration-ms="14850" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TicketBooking -->
        <test-method is-config="true" signature="afertMethod()[pri:0, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:09:25 EDT" name="afertMethod" finished-at="2021-09-10T13:09:29 EDT" duration-ms="4891" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afertMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:09:30 EDT" name="beforeMethod" finished-at="2021-09-10T13:09:50 EDT" duration-ms="20980" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="hh()[pri:2, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:09:50 EDT" name="hh" finished-at="2021-09-10T13:09:52 EDT" duration-ms="1162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hh -->
        <test-method is-config="true" signature="afertMethod()[pri:0, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:09:52 EDT" name="afertMethod" finished-at="2021-09-10T13:09:56 EDT" duration-ms="4275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afertMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:09:56 EDT" name="beforeMethod" finished-at="2021-09-10T13:10:43 EDT" duration-ms="47094" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="ff()[pri:3, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:10:43 EDT" name="ff" finished-at="2021-09-10T13:10:43 EDT" depends-on-methods="Tests.AirCanadaTest.hh" duration-ms="88" status="FAIL">
          <exception class="org.openqa.selenium.interactions.MoveTargetOutOfBoundsException">
            <message>
              <![CDATA[(699, -185) is out of bounds of viewport width (1280) and height (595)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-TTB3E54', ip: '192.168.186.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 91.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210823123856, moz:geckodriverVersion: 0.29.1, moz:headless: false, moz:processID: 5160, moz:profile: C:\Users\SHIV\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: c2cba907-1a39-4ef6-b922-1e03af7aac8f]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: (699, -185) is out of bounds of viewport width (1280) and height (595)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-TTB3E54', ip: '192.168.186.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 91.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210823123856, moz:geckodriverVersion: 0.29.1, moz:headless: false, moz:processID: 5160, moz:profile: C:\Users\SHIV\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: c2cba907-1a39-4ef6-b922-1e03af7aac8f
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:618)
at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:639)
at Pages.TicketPage.Hover(TicketPage.java:72)
at Tests.AirCanadaTest.ff(AirCanadaTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.interactions.MoveTargetOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ff -->
        <test-method is-config="true" signature="afertMethod()[pri:0, instance:Tests.AirCanadaTest@7690781]" started-at="2021-09-10T13:10:43 EDT" name="afertMethod" finished-at="2021-09-10T13:10:47 EDT" duration-ms="4117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afertMethod -->
      </class> <!-- Tests.AirCanadaTest -->
      <class name="Tests.Login">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.Login@7803bfd]" started-at="2021-09-10T13:10:47 EDT" name="beforeMethod" finished-at="2021-09-10T13:11:00 EDT" duration-ms="12276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="LoginUdemy()[pri:0, instance:Tests.Login@7803bfd]" started-at="2021-09-10T13:11:00 EDT" name="LoginUdemy" finished-at="2021-09-10T13:11:09 EDT" duration-ms="9693" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Tests.Login.LoginUdemy(Login.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginUdemy -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Tests.Login@7803bfd]" started-at="2021-09-10T13:11:09 EDT" name="afterMethod" finished-at="2021-09-10T13:11:11 EDT" duration-ms="2216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Tests.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
